### ISSUE TITLE
[1W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by 89882** [MJU-Coin/22-S-React#154]
## 📌 기능 구현 현황

 
- [ ] 화면 컴포넌트 구현
- [ ] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 상세 개발 내용

프론트 서버 셋업하고 보겸님 레포지토리 연결하여 백엔드 서버까지 셋업하였습니다
### 주요 개발 내용 2
- 상세 개발 내용
피그마를 통해 화면 설계하였습니다
![Todo 화면설계](https://user-images.githubusercontent.com/81469686/182346336-04c09fc7-68ab-4585-8d49-22e9fb6bc547.jpg)

**Comment by dojinyou** [comment]
서버 설정까지 굿!! 오늘 배운 포트 까먹지 말고 👍
