### ISSUE TITLE
[1W1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by 2020-nug** [MJU-Coin/22-S-React#155]
## 📌 기능 구현 현황
- [ ] 화면 컴포넌트 구현
- [ ] 화면 레이아웃 구현 : List View
- [ ] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 주요 개발 내용 1
- 프로젝트 생성 및 git 연동

### 주요 개발 내용 2
- Tool Figma를 이용한 화면 설계

* List화면
![TodoList image_list](https://user-images.githubusercontent.com/75975946/182349354-cd8d24e1-a9a1-4ae6-ad42-c924a499f2b8.jpg)

* Grid 화면
![TodoLsit image_grid](https://user-images.githubusercontent.com/75975946/182349383-080372eb-b6d3-4a52-abe2-b193fb27cd44.jpg)

**Comment by dojinyou** [comment]
와 어려워 보이는 데 !!! 역시 에이스 👍

**Comment by k-kbk** [comment]
모유경! 모유경!

**Comment by k-kbk** [comment]
갓유경! 갓유경!
