### ISSUE TITLE
[IW1D] 리액트 Todo 프로젝트 개발 현황

### ISSUE THREAD

**Issue by jsu5328** [MJU-Coin/22-S-React#159]
## 📌 기능 구현 현황

 
- [] 화면 컴포넌트 구현
- [] 화면 레이아웃 구현 : List View
- [] 기능 구현 : Todo 아이템 추가
- [ ] 기능 구현 : Todo 아이템 전체 목록 조회
- [ ] 기능 구현 : Todo 아이템 삭제
- [ ] 기능 구현 : Todo 아이템 수정
- [ ] 기능 구현 : Todo 아이템 상태 변경
- [ ] 화면 필터 : 완료 여부에 따른 필터
- [ ] 화면 필터 : 생성 날짜에 따른 필터
- [ ] 화면 레이아웃 구현 : Grid View

### 디자인을 했습니다.
- 맥을 쓰고 싶었습니다.. 
- '접근성은 떨어지지만 일단 눈이 편안~' 이라는 점에서 현실 고증을 했습니다.

### 기능
- 필터1과 필터2 기능이 저렇게 구현될 수 있을지 모르겠습니다. 일단 해보고 수정하겠습니다..
![image](https://user-images.githubusercontent.com/103632151/182608800-6ab2a6cc-d477-4b17-bd4b-78f15030e553.png)

**Comment by k-kbk** [comment]
굿!
